language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key: 
    secure: 9c037c6b-9092-4cf2-9245-8df51f3653ef
  app: morning-mountain-62122
  on:
    repo: thinkful-ei19/jeff-noteful-v3.1
